version: '3'
services:
  node:
    build: .
    ports:
        - "8080:80"
    env_file:
      - ./.env
    depends_on:
      - mongo
#    network_mode: "host"
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
